### ISSUE TITLE
Initial discussion

### ISSUE THREAD

**Issue by WoLfulus** [directus/api-tests#1]
Let's start a discussion in how we should proceed writing this project.

# Overview

### We should be able to

- Easily install test runner (`npm install -g ?`)
- Easily run tests against any API instances (local or remote)
- Easily run tests against docker images releases (fully automated process)
- Easily run custom tests written/stored locally

### Tests should be

- Easy to write
  - By providing an extended mocha interface
- Easy to understand
- Easy to select which suites to run or skip

### Tests should have

- Conditional execution checks
  - Tests written for features deprecated in version 7.0.0 won't run after 7.0.0
  - Tests written for features introduced in version 6.7.8 won't run before 6.7.8

# Project

## Conventions

- Core tests should live in `tests` folder
- Custom tests doesn't have folder restriction
- All tests should follow:
  - The folder name determine the current suite
  - Test files should respect the current suite name (directory)
  - Tests are written inside `.test.js` files

## Technologies

- Node.js
- Docker

## Packages

- mocha
- should.js
- axios

# Documentation

## Introduction

Explains the difference between a Suite and a Test

## Procedures

Naming conventions / "rules" to follow.

## Getting Started

How to install and run the suite(s)

## Usage

Document how CLI works. For example how to Skip a suite or Only run a single suite, and other params that can be passed in

## Extending

How to create a custom test/suite

**Comment by shealavington** [comment]
Closing discussion as we now have a structure. Improvements can still be made, but this discussion isn't relevant/required anymore.
