### ISSUE TITLE
Concise errors

### ISSUE THREAD

**Issue by benhaynes** [directus/api-tests#3]
If a test fails and it spits our an error, we should make sure it doesn't print a _huge_ amount of red text. Right now, when I get the following error, it prints **7,000 lines of red text** to the screen Haha

![Screen Shot 2019-08-16 at 1 43 35 PM](https://user-images.githubusercontent.com/522079/63187080-fe0e7d80-c02b-11e9-8ebd-c8680d326e43.png)

**Comment by shealavington** [comment]
This may have been because I was console logging things out at the time. I will try to check this.

**Comment by shealavington** [comment]
Closing for now as in my latest testing, this doesn't happen, only seeing that a test failed and what the test was. :)
