### ISSUE TITLE
Custom API Auth Token

### ISSUE THREAD

**Issue by benhaynes** [directus/api-tests#4]
When using a custom API Project, you enter the auth token ("Token used for testing authenticated requests"), but what are the permissions that need to be set for that role? Do the tests add permissions themselves? If the tests use temporary tables, how would an admin add permissions since the tables wouldn't be there yet?

Let's clarify the README so users know what to do/expect.

**Comment by shealavington** [comment]
Hmm, that's a good question @benhaynes. Something that hasn't been considered is the permissions, ideally the user should have full administrative permission, however, permissions should be tested too.

**Comment by benhaynes** [comment]
@bjgajjar @WoLfulus  @rijkvanzanten — obviously we can test against an admin static token, but does anyone have any ideas on how we could test the other auth types... as well as permissions for non-admins?

**Comment by bjgajjar** [comment]
@benhaynes - TBH, I don't have major ideas on test cases. Still trying to provide my opinion here. 

> but what are the permissions that need to be set for that role?

We can do like; use the get `roles` API and create the `user`[use the static values] of those all roles. Thus we'll have the token of all the users[role-specific].In the test cases, we can use those static token dynamically.

----

> obviously we can test against an admin static token, but does anyone have any ideas on how we could test the other auth types

- Static Token - Already described above
- Bearer Auth Token - Get the access token from `login` API and use that as a bearer token for further testing.
- Cookie - This will be for the frontend purpose only. But still, we can pass the `mode` param in `login` API; thus the response header will contain the cookie. On the success of `login`; the test case will call another API[Which must need authenticaion] containing the request header of that cookie.

**Comment by shealavington** [comment]
Thanks @bjgajjar , I've gone ahead and added placeholders for those different auth types. (Cookie/Bearer/Static)

We will test the different auth endpoints, ensuring they work correctly. Anything else that needs to be authenticated will use the static_token saved in the config, this ensures that the test won't fail because of an auth timeout or something.
